const categories = {
    "accommodation": "Accommodation",
    "accommodation.hotel": "Accommodation / Hotel",
    "accommodation.hut": "Accommodation / Hut",
    "accommodation.apartment": "Accommodation / Apartment",
    "accommodation.chalet": "Accommodation / Chalet",
    "accommodation.guest_house": "Accommodation / Guest House",
    "accommodation.hostel": "Accommodation / Hostel",
    "accommodation.motel": "Accommodation / Motel",
    "activity": "Activity",
    "activity.community_center": "Activity / Community Center",
    "activity.sport_club": "Activity / Sport Club",
    "airport": "Airport",
    "airport.private": "Airport / Private",
    "airport.international": "Airport / International",
    "airport.military": "Airport / Military",
    "airport.gliding": "Airport / Gliding",
    "airport.airfield": "Airport / Airfield",
    "commercial": "Commercial",
    "commercial.supermarket": "Commercial / Supermarket",
    "commercial.marketplace": "Commercial / Marketplace",
    "commercial.shopping_mall": "Commercial / Shopping Mall",
    "commercial.department_store": "Commercial / Department Store",
    "commercial.elektronics": "Commercial / Electronics",
    "commercial.outdoor_and_sport": "Commercial / Outdoor and Sport",
    "commercial.vehicle": "Commercial / Vehicle",
    "commercial.hobby": "Commercial / Hobby",
    "commercial.books": "Commercial / Books",
    "commercial.gift_and_souvenir": "Commercial / Gift and Souvenir",
    "commercial.stationery": "Commercial / Stationery",
    "commercial.newsagent": "Commercial / Newsagent",
    "commercial.tickets_and_lottery": "Commercial / Tickets and Lottery",
    "commercial.clothing": "Commercial / Clothing",
    "commercial.bag": "Commercial / Bag",
    "commercial.baby_goods": "Commercial / Baby Goods",
    "commercial.agrarian": "Commercial / Agrarian",
    "commercial.garden": "Commercial / Garden",
    "commercial.houseware_and_hardware": "Commercial / Houseware and Hardware",
    "commercial.florist": "Commercial / Florist",
    "commercial.furniture_and_interior": "Commercial / Furniture and Interior",
    "commercial.chemist": "Commercial / Chemist",
    "commercial.health_and_beauty": "Commercial / Health and Beauty",
    "commercial.toy_and_game": "Commercial / Toy and Game",
    "commercial.pet": "Commercial / Pet",
    "commercial.food_and_drink": "Commercial / Food and Drink",
    "commercial.convenience": "Commercial / Convenience",
    "commercial.discount_store": "Commercial / Discount Store",
    "commercial.smoking": "Commercial / Smoking",
    "commercial.second_hand": "Commercial / Second Hand",
    "commercial.gas": "Commercial / Gas",
    "commercial.weapons": "Commercial / Weapons",
    "commercial.pyrotechnics": "Commercial / Pyrotechnics",
    "commercial.energy": "Commercial / Energy",
    "commercial.wedding": "Commercial / Wedding",
    "commercial.jewelry": "Commercial / Jewelry",
    "commercial.watches": "Commercial / Watches",
    "commercial.art": "Commercial / Art",
    "commercial.antiques": "Commercial / Antiques",
    "commercial.video_and_music": "Commercial / Video and Music",
    "commercial.erotic": "Commercial / Erotic",
    "commercial.trade": "Commercial / Trade",
    "commercial.kiosk": "Commercial / Kiosk",
    "catering": "Catering",
    "catering.restaurant": "Catering / Restaurant",
    "catering.fast_food": "Catering / Fast Food",
    "catering.cafe": "Catering / Cafe",
    "catering.food_court": "Catering / Food Court",
    "catering.bar": "Catering / Bar",
    "catering.pub": "Catering / Pub",
    "catering.ice_cream": "Catering / Ice Cream",
    "catering.biergarten": "Catering / Biergarten",
    "catering.taproom": "Catering / Taproom",
    "education": "Education",
    "education.school": "Education / School",
    "education.driving_school": "Education / Driving School",
    "education.music_school": "Education / Music School",
    "education.language_school": "Education / Language School",
    "education.library": "Education / Library",
    "education.college": "Education / College",
    "education.university": "Education / University",
    "childcare": "Childcare",
    "childcare.kindergarten": "Childcare / Kindergarten",
    "entertainment": "Entertainment",
    "entertainment.culture": "Entertainment / Culture",
    "entertainment.culture.theatre": "Entertainment / Culture / Theatre",
    "entertainment.culture.arts_centre": "Entertainment / Culture / Arts Centre",
    "entertainment.culture.gallery": "Entertainment / Culture / Gallery",
    "entertainment.zoo": "Entertainment / Zoo",
    "entertainment.aquarium": "Entertainment / Aquarium",
    "entertainment.planetarium": "Entertainment / Planetarium",
    "entertainment.museum": "Entertainment / Museum",
    "entertainment.cinema": "Entertainment / Cinema",
    "entertainment.amusement_arcade": "Entertainment / Amusement Arcade",
    "entertainment.escape_game": "Entertainment / Escape Game",
    "entertainment.miniature_golf": "Entertainment / Miniature Golf",
    "entertainment.bowling_alley": "Entertainment / Bowling Alley",
    "entertainment.flying_fox": "Entertainment / Flying Fox",
    "entertainment.theme_park": "Entertainment / Theme Park",
    "entertainment.water_park": "Entertainment / Water Park",
    "entertainment.activity_park": "Entertainment / Activity Park",
    "healthcare": "Healthcare",
    "healthcare.clinic_or_praxis": "Healthcare / Clinic or Praxis",
    "healthcare.dentist": "Healthcare / Dentist",
    "healthcare.dentist.orthodontics": "Healthcare / Dentist / Orthodontics",
    "healthcare.hospital": "Healthcare / Hospital",
    "healthcare.pharmacy": "Healthcare / Pharmacy",
    "heritage": "Heritage",
    "heritage.unesco": "Heritage / UNESCO",
    "highway": "Highway",
    "highway.residential": "Highway / Residential",
    "highway.public": "Highway / Public",
    "highway.service": "Highway / Service",
    "highway.track": "Highway / Track",
    "highway.footway": "Highway / Footway",
    "highway.busway": "Highway / Busway",
    "highway.cycleway": "Highway / Cycleway",
    "highway.pedestrian": "Highway / Pedestrian",
    "highway.path": "Highway / Path",
    "highway.living_street": "Highway / Living Street",
    "highway.primary": "Highway / Primary",
    "highway.secondary": "Highway / Secondary",
    "highway.tertiary": "Highway / Tertiary",
    "highway.trunk": "Highway / Trunk",
    "highway.motorway": "Highway / Motorway",
    "leisure": "Leisure",
    "leisure.picnic": "Leisure / Picnic",
    "leisure.playground": "Leisure / Playground",
    "leisure.spa": "Leisure / Spa",
    "leisure.park": "Leisure / Park",
    "man_made": "Man Made",
    "man_made.pier": "Man Made / Pier",
    "man_made.breakwater": "Man Made / Breakwater",
    "man_made.tower": "Man Made / Tower",
    "man_made.water_tower": "Man Made / Water Tower",
    "man_made.bridge": "Man Made / Bridge",
    "man_made.lighthouse": "Man Made / Lighthouse",
    "man_made.windmill": "Man Made / Windmill",
    "man_made.watermill": "Man Made / Watermill",
    "natural": "Natural",
    "natural.forest": "Natural / Forest",
    "natural.water": "Natural / Water",
    "natural.mountain": "Natural / Mountain",
    "natural.sand": "Natural / Sand",
    "natural.protected_area": "Natural / Protected Area",
    "national_park": "National Park",
    "office": "Office",
    "office.government": "Office / Government",
    "office.company": "Office / Company",
    "office.estate_agent": "Office / Estate Agent",
    "office.insurance": "Office / Insurance",
    "office.lawyer": "Office / Lawyer",
    "office.telecommunication": "Office / Telecommunication",
    "office.educational_institution": "Office / Educational Institution",
    "office.association": "Office / Association",
    "office.non_profit": "Office / Non-Profit",
    "office.diplomatic": "Office / Diplomatic",
    "office.it": "Office / IT",
    "office.accountant": "Office / Accountant",
    "office.employment_agency": "Office / Employment Agency",
    "office.religion": "Office / Religion",
    "office.research": "Office / Research",
    "office.architect": "Office / Architect",
    "office.financial": "Office / Financial",
    "office.tax_advisor": "Office / Tax Advisor",
    "office.advertising_agency": "Office / Advertising Agency",
    "office.notary": "Office / Notary",
    "office.newspaper": "Office / Newspaper",
    "office.political_party": "Office / Political Party",
    "office.logistics": "Office / Logistics",
    "office.energy_supplier": "Office / Energy Supplier",
    "office.travel_agent": "Office / Travel Agent",
    "office.financial_advisor": "Office / Financial Advisor",
    "office.consulting": "Office / Consulting",
    "office.foundation": "Office / Foundation",
    "office.coworking": "Office / Coworking",
    "office.water_utility": "Office / Water Utility",
    "office.forestry": "Office / Forestry",
    "office.charity": "Office / Charity",
    "office.security": "Office / Security",
    "parking": "Parking",
    "parking.cars": "Parking / Cars",
    "parking.surface": "Parking / Surface",
    "parking.multistorey": "Parking / Multistorey",
    "parking.underground": "Parking / Underground",
    "parking.rooftop": "Parking / Rooftop",
    "parking.motorcycle": "Parking / Motorcycle",
    "parking.bicycles": "Parking / Bicycles",
    "pet": "Pet",
    "pet.shop": "Pet / Shop",
    "pet.veterinary": "Pet / Veterinary",
    "pet.service": "Pet / Service",
    "pet.dog_park": "Pet / Dog Park",
    "power": "Power",
    "power.generator": "Power / Generator",
    "power.line": "Power / Line",
    "power.minor_line": "Power / Minor Line",
    "power.plant": "Power / Plant",
    "power.substation": "Power / Substation",
    "power.transformer": "Power / Transformer",
    "production": "Production",
    "production.factory": "Production / Factory",
    "production.winery": "Production / Winery",
    "production.brewery": "Production / Brewery",
    "production.cheese": "Production / Cheese",
    "production.pottery": "Production / Pottery",
    "railway": "Railway",
    "railway.train": "Railway / Train",
    "railway.subway": "Railway / Subway",
    "railway.tram": "Railway / Tram",
    "railway.light_rail": "Railway / Light Rail",
    "railway.funicular": "Railway / Funicular",
    "railway.construction": "Railway / Construction",
    "railway.underground": "Railway / Underground",
    "railway.surface": "Railway / Surface",
    "rental": "Rental",
    "rental.car": "Rental / Car",
    "rental.storage": "Rental / Storage",
    "rental.bicycle": "Rental / Bicycle",
    "rental.boat": "Rental / Boat",
    "rental.ski": "Rental / Ski",
    "service": "Service",
    "service.financial": "Service / Financial",
    "service.cleaning": "Service / Cleaning",
    "service.travel_agency": "Service / Travel Agency",
    "service.post": "Service / Post",
    "service.police": "Service / Police",
    "service.vehicle": "Service / Vehicle",
    "service.beauty": "Service / Beauty",
    "service.tailor": "Service / Tailor",
    "service.funeral_directors": "Service / Funeral Directors",
    "service.bookmaker": "Service / Bookmaker",
    "service.estate_agent": "Service / Estate Agent",
    "service.locksmith": "Service / Locksmith",
    "service.taxi": "Service / Taxi",
    "service.social_facility": "Service / Social Facility",
    "service.recycling": "Service / Recycling",
    "tourism": "Tourism",
    "tourism.information": "Tourism / Information",
    "tourism.attraction": "Tourism / Attraction",
    "tourism.sights": "Tourism / Sights",
    "religion": "Religion",
    "religion.place_of_worship": "Religion / Place of Worship",
    "camping": "Camping",
    "camping.camp_pitch": "Camping / Camp Pitch",
    "camping.camp_site": "Camping / Camp Site",
    "camping.summer_camp": "Camping / Summer Camp",
    "camping.caravan_site": "Camping / Caravan Site",
    "amenity": "Amenity",
    "amenity.toilet": "Amenity / Toilet",
    "amenity.drinking_water": "Amenity / Drinking Water",
    "amenity.give_box": "Amenity / Give Box",
    "beach": "Beach",
    "beach.beach_resort": "Beach / Beach Resort",
    "adult": "Adult",
    "adult.nightclub": "Adult / Nightclub",
    "adult.stripclub": "Adult / Stripclub",
    "adult.swingerclub": "Adult / Swingerclub",
    "adult.brothel": "Adult / Brothel",
    "adult.casino": "Adult / Casino",
    "adult.adult_gaming_centre": "Adult / Adult Gaming Centre",
  };

  export default categories;